name: Deploy EC2 with Terraform.

on:
  push:
    branches:
      - main  # Runs on push to the main branch

permissions:
  id-token: write  # Enable OIDC
  contents: read

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }} 
          role-session-name: GhActionRoleSession
          aws-region: eu-west-1

        # Download previous state if it exists
      - name: Download Terraform state
        uses: actions/download-artifact@v3
        with:
          name: terraform-state
          path: .
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload Terraform state
        uses: actions/upload-artifact@v3
        with:
          name: terraform-state
          path: |
            terraform.tfstate
            terraform.tfstate.backup      

        

