name: Install gitleaks 

on:
 push:
   branches: 
     - main

jobs:
  gitleaks:
    name: gitleak install
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          wget -O gitleaks https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Verify Gitleaks Installation
        run: gitleaks version

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --source . --verbose --redact



     
